name: CI Pipeline

on: push

jobs:
    project-testing:
        runs-on: ubuntu-latest

        steps:
            - name: checkout code
              uses: actions/checkout@v6

            - name: setup python
              uses: actions/setup-python@v6
              with:
                python-version: '3.12'

            - name: cache pip dependencies
              uses: actions/cache@v4
              with:
                path: ~/.cache/pip
                key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt')}}
                restore-keys: |
                  ${{ runner.os }}-pip-

            - name: install dependencies
              run: |
                pip install -r requirements.txt

            - name: run pipeline
              env:
                ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
                SECRET_CCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET }}
                CAPSTONE_TEST: ${{ secrets.CAPSTONE_TEST }}
              run: |
                dvc repro

            - name: Run model tests
              env:
                CAPSTONE_TEST: ${{ secrets.CAPSTONE_TEST }}
              run: |
                python -m unittest tests/test_model.py

            - name: Run Flask app tests
              if: success()
              env:
                CAPSTONE_TEST: ${{ secrets.CAPSTONE_TEST }}
              run: python -m unittest tests/test_flask_app.py

            